site_name: Seika Engine
repo_url: https://github.com/Chukobyte/seika-engine
edit_uri: ""
site_description: Seika is an open source 2D/3D game engine.
site_author: Chukobyte
copyright: 'Copyright &copy; 2021 Chukobyte'

nav:
  - General:
    - Home: index.md
    - Core Concepts: general/core_concepts.md
    - Project Properties: general/project_properties.md
    - Command Line Flags: general/command_line_flags.md
  - Python API:
      - Index: python_api/index.md
      - Node: python_api/node.md
      - Camera: python_api/camera.md
      - Audio: python_api/audio.md
      - Input: python_api/input.md
      - Engine: python_api/engine.md
      - Scene: python_api/scene.md
      - Network: python_api/network.md
      - Physics: python_api/physics.md
      - Math: python_api/math.md
      - Color: python_api/color.md
      - Renderer: python_api/renderer.md
      - Assets: python_api/assets.md
  - Showcase:
      - Projects Made With Seika: showcase/projects_made_with_seika.md

plugins:
  - search
  - mermaid2

theme: readthedocs
